apiVersion: apps/v1
kind: Deployment
metadata:
  name: okk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okk
  template:
    metadata:
      labels:
        app: okk
    spec:
      containers:
      - image: okteto.dev/okk:latest
        name: okk
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "4674e713-8675-4b83-911d-4a0bfd5a5a6d"
        - name: Vless_Path
          value: "/hjjkjkt89jh"
        - name: Vmess_UUID
          value: "4674e713-8675-4b83-911d-4a0bfd5a5a6d"
        - name: Vmess_Path
          value: "/fchhgjjhjggg446mn"
        - name: Share_Path
          value: "/v2link"
